import React, { useContext, useEffect, useRef, useState } from 'react';
import {
  View,
  Text,
  FlatList,
  TouchableOpacity,
  StyleSheet,
  TextInput,
  Image,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
  TouchableWithoutFeedback,
} from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  runOnJS,
} from 'react-native-reanimated';
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
} from 'react-native-gesture-handler';
import { ReactNativeZoomableView } from '@openspacelabs/react-native-zoomable-view';

import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import BrickBorder from '../../component/floorplan/BrickBorder';
import GridLines from '../../component/floorplan/GridLines';
import { apiRequest } from '../../utils/api';
import {  API_URL, PROD_API_URL } from '@env';
import { captureRef } from 'react-native-view-shot';
import RNPrint from 'react-native-print';
import RNHTMLtoPDF from 'react-native-html-to-pdf';
import { useNavigation } from '@react-navigation/native';
import SideComponent from '../../component/floorplan/SideComponent';
import { SafeAreaView } from 'react-native-safe-area-context';
import RNFS from 'react-native-fs';
import { UserContext } from '../../hooks/context/UserContext';

const SCALE = 30;

const BRICK_WIDTH = 15;
const BRICK_HEIGHT = 15;

export default function FloorPlan({ route }) {

  const { id, name } = route.params;
  const [elements, setElements] = useState([]);
  const [roomWidthFt, setRoomWidthFt] = useState(15);
  const [roomHeightFt, setRoomHeightFt] = useState(10);
  const [selectedId, setSelectedId] = useState(null);
  const zoomRef = useRef();
  const panRef = useRef();
  const roomWidthPx = roomWidthFt * SCALE;
  const roomHeightPx = roomHeightFt * SCALE;
  const navigation = useNavigation();

  const [isDragging, setIsDragging] = useState(false);
  const [assets, setAssets] = useState([]);
  const canvasRef = useRef();
  const {userId, username, mobileNo} = useContext(UserContext) || {};

  // const captureCanvasAsImage = async () => {
  //   try {
  //     const uri = await captureRef(canvasRef, {
  //       format: 'png',
  //       quality: 1,
  //     });

  //     console.log('Captured image URI:', uri);

  //     // Send the image to print
  //     await RNPrint.print({ filePath: uri });
  //   } catch (error) {
  //     console.error('Error capturing and printing canvas:', error);
  //   }
  // };
  const captureCanvasAsImage = async () => {
  try {
    const uri = await captureRef(canvasRef, {
      format: 'png',
      quality: 1,
    });

    const base64Data = await RNFS.readFile(uri, 'base64');
    const base64Image = `data:image/png;base64,${base64Data}`;

    const currentDate = new Date().toLocaleString('en-IN', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
    });

    const elementGrid = elements.map((el, idx) => {
      const title = el.title || el.src.split('/').pop();
      const widthInches = (el.width / 10).toFixed(2);
      const heightInches = (el.height / 10).toFixed(2);
      // <div style="font-size:12px; color:#555;">${widthInches}in x ${heightInches}in</div>

      return `
        <div style="width:48%; margin:1%; display:inline-block; text-align:center; break-inside: avoid;">
          <img src="${el.src}" style="width:100%; max-height:150px; object-fit:contain; border-radius:6px;" />
          <div style="margin-top:6px; font-weight:500;">${title}</div>
          
        </div>
      `;
    }).join('');

    const html = `
      <html>
        <head>
          <style>
            @page {
              margin: 30px;
              border: 3px solid #000;
            }
            body {
              font-family: Helvetica, Arial, sans-serif;
              font-size: 13px;
              color: #000;
              margin: 30px;
            }
          </style>
        </head>
        <body>
          <h2 style="text-align:center; margin-bottom:20px;">FLOOR PLAN REPORT</h2>

          <img src="${base64Image}" style="width:100%; max-height:650px; object-fit:contain; border:1px solid #ccc; border-radius:8px;" />

          <div style="display:flex; justify-content:space-between; margin-top:20px;">
            <div style="width:48%;">
              <p><strong>Company:</strong> SEEB DESIGN PVT LTD</p>
              <p><strong>Email:</strong> info@seeb.in</p>
              <p><strong>Contact:</strong> 18005703133</p>
              <p><strong>Address:</strong> S.No 29/13b, Wadachiwadi Road,<br/>Jakat Naka, Undri, Pune,<br/>Maharashtra - 411060</p>
            </div>
            <div style="width:48%;">
              <p><strong>Room Name:</strong> ${name}</p>
              <p><strong>Generated By:</strong> ${username}</p>
              <p><strong>Mobile:</strong> ${mobileNo}</p>
              <p><strong>Date:</strong> ${currentDate}</p>
            </div>
          </div>

          <h3 style="margin-top:30px; border-bottom:1px solid #ccc; padding-bottom:6px;">Element List</h3>

          <div style="display:flex; flex-wrap:wrap; justify-content:space-between;">
            ${elementGrid}
          </div>
        </body>
      </html>
    `;

    const pdf = await RNHTMLtoPDF.convert({
      html,
      fileName: 'floorplan',
      base64: false,
    });

    await RNPrint.print({ filePath: pdf.filePath });

  } catch (error) {
    console.error('Error capturing and printing PDF:', error);
  }
};

  useEffect(() => {
    fetchAssets()
  }, [])

  const fetchAssets = async () => {
    const response = await apiRequest("GET", `/assets/room/${id}`);
    if (response) {
      setAssets(response);
    } else {
      setAssets([])
      console.log("Error fetching assets", response);
    }
  }


  const canvasScale = useSharedValue(1);
  const pinchGesture = Gesture.Pinch().onUpdate((e) => {
    canvasScale.value = Math.max(0.5, Math.min(e.scale, 3));
  });

  const animatedCanvasStyle = useAnimatedStyle(() => ({
    transform: [{ scale: canvasScale.value }],
  }));

  const addElement = (item) => {
    const width = item.width * SCALE;
    const height = item.length * SCALE;
    const randomX = 20 + Math.random() * (roomWidthPx - width - 40);
    const randomY = 20 + Math.random() * (roomHeightPx - height - 40);

    setElements((prev) => [
      ...prev,
      {
        src: API_URL + item.file,
        ...item,
        id: `${item.id}-${Date.now()}`,
        width,
        height,
        x: randomX,
        y: randomY,
      },
    ]);
  };

  const handleGetDesignWithAI = async () => {
    const uri = await captureRef(canvasRef, {
      format: 'png',
      quality: 1,
    });

    navigation.navigate('ElementsDesign', { elements, floorPlanImage: uri, width: roomWidthFt, height: roomHeightFt, name });
    // navigation.navigate('GeminiAi', { elements, floorPlanImage: uri });
  }

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <KeyboardAvoidingView
        style={{ flex: 1 }}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <SafeAreaView style={styles.container}>
          {/* Inputs */}
          <View style={styles.inputRow}>
            <Text style={styles.label}>Width (ft):</Text>
            <TextInput
              style={styles.input}
              value={roomWidthFt.toString()}
              onChangeText={(val) => setRoomWidthFt(val)}
              keyboardType="numeric"
              inputMode="decimal"
            />
            <Text style={styles.label}>length (ft):</Text>
            <TextInput
              style={styles.input}
              value={roomHeightFt.toString()}
              onChangeText={(val) => setRoomHeightFt(val)}
              keyboardType="numeric"
              inputMode="decimal"
            />
            <TouchableOpacity onPress={captureCanvasAsImage} style={styles.printBtn}>
              <Icon name="printer" size={22} color="#000" />
            </TouchableOpacity>
          </View>

          <TouchableOpacity onPress={handleGetDesignWithAI} style={{ backgroundColor: '#007bff', padding: 12, borderRadius: 8, alignItems: 'center', marginHorizontal: 20, marginTop: 10 }}>

            <Text style={{ fontSize: 14, color: '#fff', textAlign: 'center', }}>Get Space Design With AI</Text>
          </TouchableOpacity>

          {/* Scroll + Zoom */}
          <ReactNativeZoomableView
            ref={canvasRef}
            maxZoom={1.5}
            minZoom={0.5}
            zoomStep={0.5}
            initialZoom={0.65}
            bindToBorders={true}
            contentWidth={roomWidthPx + BRICK_WIDTH * 2}
            contentHeight={roomHeightPx + BRICK_HEIGHT * 2}
            // onZoomAfter={this.logOutZoomState}
            style={{
              // padding: 10,
              // backgroundColor: '#f0eae2',
            }}
          >
            {/* <ZoomableCanvas contentWidth={roomWidthPx} contentHeight={roomHeightPx}> */}
            <TouchableWithoutFeedback onPress={() => setSelectedId(null)}>
              <View
                style={[
                  styles.canvas,
                  {
                    width: roomWidthPx + BRICK_WIDTH * 2,
                    height: roomHeightPx + BRICK_HEIGHT * 2,
                  },
                ]}
              >
                {/* Side labels (A, B, C, D) */}
                <SideComponent width={roomWidthPx} height={roomHeightPx} />
                {/* Brick border */}
                <BrickBorder width={roomWidthPx} height={roomHeightPx} />


                {/* Grid and elements */}
                <View
                  style={{
                    position: 'absolute',
                    top: BRICK_HEIGHT,
                    left: BRICK_WIDTH,
                    width: roomWidthPx,
                    height: roomHeightPx,
                  }}
                >
                  <GridLines width={roomWidthPx} height={roomHeightPx} />

                  <Text style={styles.roomLabel}>
                    {name} ({roomWidthFt}ft x {roomHeightFt}ft)
                  </Text>

                  {elements.map((item) => (
                    <DraggableItem
                      key={item.id}
                      {...item}
                      canvasWidth={roomWidthPx}
                      canvasHeight={roomHeightPx}
                      isSelected={item.id === selectedId}
                      onSelect={() => setSelectedId(item.id)}
                      zoomRef={zoomRef}
                      panRef={panRef}
                      setIsDragging={setIsDragging}
                      panEnabled={isDragging}
                      setElements={setElements}
                    />
                  ))}
                </View>
              </View>
            </TouchableWithoutFeedback>
            {/* </ZoomableCanvas> */}

          </ReactNativeZoomableView>

          {/* Bottom palette */}
          {/* <TouchableOpacity style={styles.printButton} onPress={handleSubmit}>
              <Text style={styles.printButtonText}>Submit</Text>
            </TouchableOpacity> */}
          <View style={styles.palette}>
            <FlatList
              horizontal
              data={assets}
              keyExtractor={(item) => item.id}
              renderItem={({ item }) => (
                <TouchableOpacity
                  style={styles.paletteItem}
                  onPress={() => addElement(item)}
                >
                  <Image source={{ uri: API_URL + item.file }} style={{ width: 50, height: 50 }} resizeMode='contain' />
                  <Text style={{ fontSize: 12, color: '#000' }}>{item.title}</Text>
                </TouchableOpacity>
              )}
            />
          </View>
        </SafeAreaView>
      </KeyboardAvoidingView>
    </GestureHandlerRootView >
  );
}


function DraggableItem({
  id,
  src,
  width,
  height,
  x,
  y,
  canvasWidth,
  canvasHeight,
  title,
  panRef,
  zoomRef,
  setIsDragging,
  isSelected,
  onSelect,
  setElements
}) {
  const tx = useSharedValue(x);
  const ty = useSharedValue(y);
  const w = useSharedValue(width);
  const h = useSharedValue(height);
  const scale = useSharedValue(1);
  const rotation = useSharedValue(0);
  const startX = useSharedValue(x);
  const startY = useSharedValue(y);

  const pan = Gesture.Pan()
    .onBegin(() => runOnJS(setIsDragging)(false))
    .onStart(() => {
      startX.value = tx.value;
      startY.value = ty.value;
    })
    .onUpdate((e) => {
      tx.value = startX.value + e.translationX;
      ty.value = startY.value + e.translationY;
    })
    .onFinalize(() => runOnJS(setIsDragging)(true))
    .withRef(panRef);

  const resizeRight = Gesture.Pan()
    .onStart(() => {
      startX.value = w.value;
    })
    .onUpdate((e) => {
      w.value = Math.max(20, startX.value + e.translationX);
    });

  const resizeBottom = Gesture.Pan()
    .onStart(() => {
      startY.value = h.value;
    })
    .onUpdate((e) => {
      h.value = Math.max(20, startY.value + e.translationY);
    });

  const gesture = Gesture.Simultaneous(pan);
  const animatedStyle = useAnimatedStyle(() => ({
    position: 'absolute',
    width: w.value,
    height: h.value,
    transform: [
      { translateX: tx.value },
      { translateY: ty.value },
      { scale: scale.value },
      { rotateZ: `${rotation.value}rad` },
    ],
  }));

  const labelStyle = useAnimatedStyle(() => ({
    position: 'absolute',
    top: ty.value + 20, // slightly above the item
    left: tx.value + w.value / 2, // move to center
    transform: [{ translateX: -w.value / 2 }], // shift back to center align
  }));



  return (
    <>
      {/* <Animated.Text
        style={[styles.elementLabel, labelStyle]}
        pointerEvents="none"
      >
        {title + '\n' + `(${(w.value / SCALE).toFixed(1)}ft x ${(h.value / SCALE).toFixed(1)}ft)`}
      </Animated.Text> */}

      <GestureDetector gesture={gesture} simultaneousHandlers={zoomRef}>
        <Animated.View style={animatedStyle}>
          <TouchableOpacity
            activeOpacity={1}
            onPress={onSelect}
            style={{ width: '100%', height: '100%' }}
          >
            <Image source={{ uri: src }} style={{ width: '100%', height: '100%' }} resizeMode='contain' />
          </TouchableOpacity>
          {/* Rotate */}
          {isSelected && (
            <>
              <TouchableOpacity
                style={styles.rotateBtn}
                onPress={() => {
                  rotation.value += Math.PI / 2;
                  // const temp = w.value;
                  // w.value = h.value;
                  // h.value = temp;
                }}
              >
                <Text style={{ fontSize: 25 }}>⟳</Text>
              </TouchableOpacity>

              {/* Resize Right */}
              <GestureDetector gesture={resizeRight}>
                <Animated.View style={styles.resizeHandleRight}>
                  <Icon name="arrow-collapse-horizontal" size={25} color="#333" />
                </Animated.View>
              </GestureDetector>

              {/* Resize Bottom */}
              <GestureDetector gesture={resizeBottom}>
                <Animated.View style={styles.resizeHandleBottom}>
                  <Icon name="arrow-collapse-vertical" size={25} color="#333" />
                </Animated.View>
              </GestureDetector>

              {/* Delete Icon */}
              <TouchableOpacity
                style={styles.deleteIcon}
                onPress={() => {
                  runOnJS(setElements)((prev) => prev.filter((el) => el.id !== id));
                  runOnJS(setIsDragging)(false);
                }}
              >
                <Icon name="delete" size={25} color="red" />
              </TouchableOpacity>
            </>
          )}
        </Animated.View>
      </GestureDetector>
    </>
  );
}


const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  canvas: {
    backgroundColor: '#ffffff',
    // borderWidth: 2,
    // borderColor: '#aaa',
    margin: 20,
    position: 'relative',
    borderRadius: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  palette: {
    flexDirection: 'row',
    padding: 10,
    borderTopWidth: 1,
    borderColor: '#ccc',
    backgroundColor: '#fafafa',
  },
  paletteItem: {
    alignItems: 'center',
    marginRight: 12,
  },
  inputRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 10,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#ccc',
    backgroundColor: '#fafafa',
  },
  label: { fontSize: 14, marginRight: 5, color: '#333' },
  input: {
    width: 70,
    height: 40,
    borderWidth: 1,
    borderColor: '#aaa',
    paddingHorizontal: 6,
    marginRight: 10,
    borderRadius: 6,
    backgroundColor: '#fff',
    color: '#333',
  },
  elementLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#000',
    backgroundColor: 'rgba(255,255,255,0.5)', // subtle background
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    textAlign: 'center',
    zIndex: 999,
    position: 'absolute',
  },
  roomLabel: {
    position: 'absolute',
    top: -100,
    left: 80,
    fontSize: 25,
    color: 'black',
    fontWeight: 'bold',
  },
  rotateBtn: {
    position: 'absolute',
    top: -12,
    right: -12,
    backgroundColor: '#fff',
    padding: 4,
    borderRadius: 20,
    elevation: 5,
    zIndex: 10,
  },
  resizeHandleRight: {
    position: 'absolute',
    right: -12,
    top: '50%',
    marginTop: -10,
    backgroundColor: '#fff',
    padding: 4,
    borderRadius: 20,
    zIndex: 10,
    elevation: 5,
  },
  resizeHandleBottom: {
    position: 'absolute',
    bottom: -12,
    left: '50%',
    marginLeft: -10,
    backgroundColor: '#fff',
    padding: 4,
    borderRadius: 20,
    zIndex: 10,
    elevation: 5,
  },
  deleteIcon: {
    position: 'absolute',
    top: -12,
    left: -12,
    backgroundColor: '#fff',
    padding: 4,
    borderRadius: 20,
    elevation: 5,
    zIndex: 10,
  },
  printBtn: {
    marginLeft: 10,
    backgroundColor: '#eaeaea',
    padding: 8,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    height: 35,
  },
  printButton: {
    backgroundColor: '#007bff',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignSelf: 'center',
    marginBottom: 10,
    marginLeft: 10,
  },
  printButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
