require Pod::Executable.execute_command('node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})',
  __dir__
]).strip

platform :ios, min_ios_version_supported

prepare_react_native_project!

# Optional: react-native-permissions
permissions_setup = '../node_modules/react-native-permissions/scripts/setup.rb'
require permissions_setup if File.exist?(permissions_setup)

setup_permissions([
  'LocationAccuracy',
  'LocationWhenInUse',
])

use_frameworks! :linkage => :static

target 'seeb' do
  $RNFirebaseAsStaticFramework = true
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :fabric_enabled => false
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
